## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: "\u2753 Discord Community of GDSC - UTM"
    url: "https://discord.gg/2tW4jfVd"
    about: "Please ask support questions or discuss #help"